-- This is an automatically generated SQL table. This has been generated by the RADIAN tool (developer Mr. Paddy Gorry)
-- This table is for use in DEMO Lab Exam 2a in CS621 2023/2024. 

--DROP TABLE IF EXISTS DemoLabExam2aTable CASCADE; 

CREATE TABLE DemoLabExam2aTable ( 
	pkid SERIAL PRIMARY KEY NOT NULL, 
	cloc GEOMETRY DEFAULT ST_GeomFromText('POINT(0,51)', 4326), 
	amount INTEGER, 
	checksum TEXT NOT NULL, 
	ccTS TIMESTAMP NOT NULL,
	creditcard TEXT NOT NULL
); 

-- Spatial index is now created
CREATE INDEX DemoLabExam2aTable_spatial_index ON DemoLabExam2aTable USING gist (cloc); 

-- Table inserts will follow. 

INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.557082433545272,-34.0057407720696),4326), 71, 'IlKCcDMuy', '2022-03-18 06:35:40',	'374283450309042');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.551877136103798,-34.00547530451646),4326), 260, 'cDN9NghAQ', '2022-02-19 14:21:08',	'374288756950894');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.547660580250035,-33.99927440819535),4326), 350, '1zhRqzbmh', '2022-02-11 09:31:56',	'374283399517713');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.553606457275343,-34.00853217450411),4326), 235, 'iMfMGQhrd', '2022-04-07 01:03:20',	'374288071977929');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54987704488739,-34.00856361027305),4326), 269, 'gwXPslvGL', '2022-03-21 19:24:53',	'374283339119216');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.553599465985165,-33.999458103963484),4326), 349, 'C8vFAQ0BE', '2022-02-09 12:34:01',	'374283423891472');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.549043448315082,-34.00850519106085),4326), 103, 'tySUIRr0F', '2022-03-28 23:55:02',	'374283726731995');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.548070609575138,-33.99480366795875),4326), 148, 'Ici3ATWF3', '2022-02-07 11:43:51',	'374288148650392');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57209420594077,-34.00665716852093),4326), 202, 'hP2GpO175', '2022-02-28 21:20:33',	'374288150342797');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.569915121498088,-33.99685390657065),4326), 230, 'NPAUenAMU', '2022-04-29 16:14:02',	'374283749557054');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.556701448704537,-34.002761725745664),4326), 360, 'NK4YhMy4y', '2022-02-26 20:11:33',	'374283180128951');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57252101041742,-33.99481464536604),4326), 158, '1sGMJnypd', '2022-03-27 23:57:33',	'374283567782081');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.563492326399007,-34.0068236006866),4326), 343, 'G1lIuaIcv', '2022-02-24 17:39:33',	'374283423918143');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54619920666712,-34.0153927339549),4326), 222, 'dUuz5RZab', '2022-04-21 01:52:59',	'374288527554652');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54465613369464,-34.0251043443651),4326), 94, '1dyZ8FFoZ', '2022-02-23 00:49:35',	'374283188122329');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.559249886586592,-34.01996701640442),4326), 213, 'xz8eoFhON', '2022-03-19 04:32:51',	'374288243778528');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.571350739542286,-33.98672264963391),4326), 436, '1JIbxbeV4', '2022-04-29 19:53:16',	'374283605060433');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.548335430787585,-34.01095963045037),4326), 419, 'K8VymlPZm', '2022-03-27 12:01:14',	'374288946638987');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.564143870754812,-33.97770562084893),4326), 236, 'uadP232Fd', '2022-03-26 03:10:58',	'374288074419937');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.540287120932486,-33.98963204027227),4326), 429, 'teuoEnLfV', '2022-04-14 10:21:07',	'374288364637834');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.535383128360408,-34.016977888549114),4326), 202, 'g1rO4DGOg', '2022-02-05 15:43:13',	'374283174141291');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.584253013728105,-34.02079106247986),4326), 139, 'kQVq7SgPo', '2022-02-18 18:47:53',	'374288923308760');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.548140819257206,-34.01727963741748),4326), 118, 'GraVsj6oN', '2022-02-03 18:35:14',	'374283460586761');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.53681563348373,-33.99747095511342),4326), 255, 'lyQ4A82Ed', '2022-04-23 23:04:37',	'374288332938512');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5527248124023,-34.034694895179186),4326), 81, 'w0XzI9vqX', '2022-04-19 13:03:43',	'374288644347253');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.582993040888155,-34.016039749634835),4326), 299, 'g00VfGFQ9', '2022-04-14 17:31:23',	'374288058999789');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54645413124008,-33.97680393931199),4326), 223, '8mG67lIhD', '2022-04-12 20:22:40',	'374283326682895');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.594396341471167,-34.00144630237468),4326), 498, 'w3tqKG8vf', '2022-03-28 12:18:24',	'374288542083919');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.534650356055288,-34.02509611957018),4326), 498, 'EMeVQvvN1', '2022-04-13 05:44:47',	'374283969543420');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.574833278518508,-33.963276443332845),4326), 80, 'OsRZzNcUe', '2022-03-17 19:48:50',	'374288896821575');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.605564367541717,-34.01817195352996),4326), 328, 'gdZi8yjc0', '2022-04-16 13:47:53',	'374288036756954');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.611352766072486,-33.99426965472074),4326), 322, 'BYOqcSqOe', '2022-04-02 07:35:19',	'374288546043927');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.535835720377165,-33.98560825234876),4326), 210, 'kO49cyefn', '2022-02-17 18:39:47',	'374288833581159');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.56751207862424,-34.001902400159814),4326), 219, 'Ijh8PYIfT', '2022-03-02 14:03:55',	'374283777337668');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.556780586519544,-33.9979831690685),4326), 466, 'fdalsiIfy', '2022-03-10 22:24:08',	'374288589449049');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57210073001689,-34.00273083920173),4326), 218, '2ZVYQSZm4', '2022-02-24 08:29:54',	'374288919906031');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.575255912633477,-33.98858735199824),4326), 494, 'GuxrMt03k', '2022-03-23 14:37:15',	'374283526582929');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.556494318513668,-33.995526118562054),4326), 438, 'BcyVN9Lqv', '2022-02-04 18:26:36',	'374283033958331');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.562968409773067,-34.00949540016212),4326), 242, 'DPGENdEi1', '2022-02-06 09:53:02',	'374283530762434');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.582871675555015,-33.98816394887976),4326), 89, 'iA9QHD8zj', '2022-03-08 06:48:58',	'374283370078883');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.548296280687207,-33.99221436752071),4326), 277, 'qhSkpTgyh', '2022-04-01 00:42:41',	'374288750216250');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.574842004805486,-33.990107833389736),4326), 423, 'p0ZXK2dOk', '2022-04-18 10:43:51',	'374288978303963');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.555743582856195,-33.99102855577151),4326), 445, 'KpTbt2Xvz', '2022-02-16 05:18:28',	'374288206633611');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59492992860812,-33.97376909126324),4326), 297, 'rGfLrzSY9', '2022-02-16 17:09:11',	'374283383966199');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.540330401670875,-34.00632792760774),4326), 361, 'tX0kkGi3S', '2022-02-21 11:33:00',	'374288341938628');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.598270324565625,-33.982560081923204),4326), 165, '3bp6IWX1V', '2022-02-20 13:35:44',	'374288585242737');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.542600461844888,-33.992231122200295),4326), 428, 'OFCy8W4Xe', '2022-03-01 06:08:25',	'374283935178111');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54980054679841,-34.010626193179185),4326), 295, 'Ysg1G9Xo4', '2022-04-02 14:17:22',	'374288938188892');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.609071201536658,-33.997093873984255),4326), 253, 'O4wDAv4Xa', '2022-02-05 14:35:47',	'374283444181549');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.567286116421062,-33.99819319075285),4326), NULL, 'ieZWkzbnK', '2022-04-26 19:32:06',	'374288518969943');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.58827130402401,-34.01737968656681),4326), 405, '3lYHI03U0', '2022-03-15 06:24:00',	'374283722176799');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.544311468321077,-34.040501858085946),4326), 466, 'QpChPA4wf', '2022-04-14 15:50:37',	'374288718105934');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.554646660762934,-34.04381141651178),4326), 143, 'HSnm2LYj5', '2022-04-28 06:11:54',	'374288504962084');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57057898691507,-34.030863484239696),4326), 357, 'ADNnaivKt', '2022-04-07 06:43:56',	'374283040296857');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59572977677554,-34.05000228946855),4326), 101, '7rcz8kH5R', '2022-03-21 16:39:02',	'374288379227530');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.610394998401894,-33.97911722930997),4326), 253, 'kn2yh1cCe', '2022-04-07 12:18:07',	'374283687280677');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.506444184405243,-34.02122693933124),4326), 129, 'HanT4QyLy', '2022-04-30 00:54:17',	'374288139107204');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.621459723156033,-34.00857076775224),4326), 163, 'FWwNP697D', '2022-02-19 06:15:16',	'374283448157875');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.569716829897512,-33.985943732385635),4326), 440, 'lc78zToNk', '2022-03-28 03:28:59',	'374288272543694');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.526194226419047,-34.03628714831755),4326), 398, 'MCr5CpaRF', '2022-04-09 15:58:00',	'374288388884792');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.529507750449888,-33.97989009381865),4326), 199, 'ZfFIEutSz', '2022-03-17 13:19:06',	'374288745436757');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.594309207530863,-34.064809396500415),4326), 348, 'zLdGyfHJk', '2022-03-16 07:23:36',	'374283878678069');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.508813985661984,-34.05822299039741),4326), NULL, 'ClBVUBZ3Q', '2022-03-29 07:17:14',	'374283361584600');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.587370000622066,-34.03259548521683),4326), 194, 'Daewq8pT0', '2022-04-20 06:00:49',	'374283822111514');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.599253517025186,-34.06475439682182),4326), 479, 'd5U31P97k', '2022-02-21 10:58:22',	'374288995943528');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.502502922636307,-33.965572574845915),4326), 128, 'PpSNZtmT3', '2022-02-08 23:30:06',	'374283124965187');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.523462712989346,-33.999188043160956),4326), 126, 'yGHn0w77w', '2022-04-28 07:28:39',	'374283126524008');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.528268972301202,-34.011705557683456),4326), 118, 'WJD4jgFxH', '2022-04-27 05:06:24',	'374283873572606');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.53657167023381,-33.998083065416736),4326), 362, 'y4OkIy1r3', '2022-04-24 09:27:37',	'374283227653615');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52280158035126,-33.986986042373886),4326), 362, 'eWsBznSI7', '2022-04-09 09:05:42',	'374288210143540');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.520734676393413,-34.01684848738398),4326), 419, 'G081EtsAS', '2022-03-19 14:25:52',	'374283640462883');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.523455294333555,-33.99681567625023),4326), NULL, 'ZrVUHR6mj', '2022-04-21 21:26:13',	'374283056081227');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.50189338761113,-34.016783317614134),4326), 285, 'RIf0bRaKu', '2022-02-21 17:32:35',	'374283884346123');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.523444491393732,-34.02389577308106),4326), 401, 'hRkx3dnpo', '2022-02-19 14:59:52',	'374288101818051');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.507810621198963,-34.02803998984603),4326), 260, '7bk75uCh8', '2022-04-24 22:40:32',	'374283963595533');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.53438033946979,-34.01818629614592),4326), NULL, 'iKi4ovJna', '2022-04-02 17:17:15',	'374288080707929');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.538413652902626,-34.01324469049883),4326), 455, 'f2EQEE6Gh', '2022-04-26 01:44:36',	'374288776907189');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57234974864654,-34.01128312563354),4326), NULL, 'sQTYpBvFy', '2022-02-01 13:53:56',	'374283643993603');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.548536679072004,-34.02407292987947),4326), 84, 'dfxuslwbI', '2022-02-06 00:35:55',	'374288483624663');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.515529657238595,-34.02180727219429),4326), 340, 'emdPVasHa', '2022-04-20 21:01:11',	'374288279981764');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59227443477619,-34.02456671930606),4326), 378, '0gEGR9ODD', '2022-04-24 10:43:51',	'374288025436550');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.570244656385142,-34.010041510306785),4326), 181, 'YMcFAGIIQ', '2022-02-26 15:05:15',	'374283044448124');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.529923548088828,-33.94447781973119),4326), 355, 'lpq0CWNcw', '2022-03-13 11:03:01',	'374283567246111');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.49166055137244,-34.00009203256304),4326), 137, 'akWEHdJTg', '2022-02-28 13:36:22',	'374288802602002');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5095834215286,-34.0290004945085),4326), 338, '6qM3HjaVX', '2022-02-08 10:49:17',	'374283052497518');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.51205869006412,-34.03709378646342),4326), 385, 'X0jYEL6wP', '2022-04-03 20:54:49',	'374283579948233');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.564839589348832,-34.030873795531974),4326), 373, 'Wsqw6sBL4', '2022-03-28 05:55:02',	'374288294510242');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.615866447080908,-34.03955016523554),4326), 61, 'A8lCsgaaI', '2022-03-06 01:08:21',	'374283277275632');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.45840809148528,-33.99344352340944),4326), 85, 'WsLDQG7Ce', '2022-02-25 05:43:36',	'374283365246214');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.533970945495305,-34.08157446369153),4326), 125, 'CiR06raT3', '2022-02-09 04:09:28',	'374283928743939');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52961749815633,-34.03361445610748),4326), 111, 'PURzw1OsV', '2022-04-26 20:31:39',	'374283524054202');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.533200413933635,-34.03677280548845),4326), 490, 'K7Y82v0N7', '2022-03-24 00:30:39',	'374283079033825');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.46295831818937,-33.982862628890686),4326), 349, 'FDYoVoBoz', '2022-03-23 11:58:06',	'374288157079525');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.55428056397666,-33.96816177793993),4326), 159, '8g2XcKxij', '2022-03-04 17:05:56',	'374283257624874');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.571263842774062,-33.94956268250086),4326), 249, 'J787q85wW', '2022-04-05 19:49:49',	'374283436942643');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.641221350212515,-33.98507686955241),4326), 166, 'T7BUmvjYw', '2022-02-18 05:42:09',	'374283981571391');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.457756177635193,-33.98310858692506),4326), 456, 'PNyW3QBRq', '2022-03-24 17:51:57',	'374283109788687');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.503152033023454,-33.9180439347052),4326), 427, 'tVdVF1x9B', '2022-02-27 11:36:39',	'374283434180386');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54333358667288,-34.043415265447756),4326), 206, 'GiE9cjn8Y', '2022-03-23 23:38:45',	'374288132595504');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.544823355130923,-33.9671403022063),4326), 194, 'qwHLIun31', '2022-04-23 16:18:41',	'374288133973767');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.533370648578178,-33.99988151763439),4326), 129, 'avtcLqyQw', '2022-04-11 04:56:38',	'374283991942483');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.544364911265806,-33.98059459955118),4326), 299, 'CDOhMIR5h', '2022-03-21 04:22:41',	'374283673567699');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5252169772097,-33.99279562640643),4326), 87, 'q98E7HMC5', '2022-03-17 23:55:14',	'374283951678143');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.530349222941812,-33.99753988518609),4326), 232, 'nZsSyjHEU', '2022-03-11 20:20:49',	'374283234634665');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.573809844819586,-33.97721140780467),4326), 225, 'jUXe1w9Yn', '2022-03-13 07:26:18',	'374283272480633');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.574326445182017,-33.99302831435909),4326), 144, '71sSOihqP', '2022-02-01 12:13:45',	'374288245789861');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.557234652668466,-33.9713001535838),4326), 480, 'nilwCudyC', '2022-03-20 07:16:00',	'374283402915920');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57171252513808,-34.00575661635367),4326), 490, 'LPu0R022D', '2022-03-03 03:19:40',	'374283892944976');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.527310707993802,-33.94605356911368),4326), 442, 'pxSM2nyYp', '2022-04-18 16:32:36',	'374283059005959');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5124172598406,-33.992057662474636),4326), 134, '6NsX75kbL', '2022-02-12 08:00:59',	'374283723261327');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.51287121870415,-34.00098510933727),4326), 341, 'gGchXNRFT', '2022-04-28 12:19:52',	'374283922470299');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.578789048860624,-33.956906435373014),4326), 500, 'dGMRDRkWz', '2022-04-17 13:11:22',	'374283660191115');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.543605151465687,-33.98980985050764),4326), 478, 'pxps18pUc', '2022-03-31 15:41:09',	'374283340169598');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.561741333714277,-34.01600872326002),4326), 169, 'KH0RygbW7', '2022-02-07 09:07:55',	'374288650122707');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.504273964484124,-34.05496415722274),4326), 331, 'miZoBtNjP', '2022-03-02 06:50:26',	'374283261450225');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.48854395222234,-34.03659538146769),4326), 428, 'eEhjoc27I', '2022-03-15 20:33:39',	'374283730136900');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.575514371232014,-34.023776258694426),4326), 60, 'F0lBDcuqF', '2022-04-27 11:45:10',	'374283227160587');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.570410985537364,-33.94548123443166),4326), 402, 'cmvJdfMT0', '2022-03-01 18:19:18',	'374283566669925');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.557063326886066,-34.02293775732301),4326), 448, 'AyJm8evDs', '2022-03-16 20:03:55',	'374288275676483');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.614329298687853,-34.01489884201905),4326), 478, 'OWndfS0IB', '2022-03-23 08:06:57',	'374288474514055');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.4630974136562,-33.93735647353988),4326), 60, 'zocOAzZBR', '2022-03-05 01:32:23',	'374283049455009');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.537144698892654,-34.012706782554595),4326), 145, 'xHZWpnVL6', '2022-03-09 19:21:06',	'374288153443709');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.584454387808716,-33.91697858048131),4326), 439, '3gjBNpW7o', '2022-02-25 01:13:50',	'374288380284405');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.607923020664845,-34.0100698230325),4326), 182, 'a8Kvlgg8Y', '2022-02-20 02:34:01',	'374283382355600');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.450938754452704,-34.056248973146175),4326), 494, 'kNfBM9HVh', '2022-03-11 03:01:03',	'374283374465185');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.49490104046055,-34.0344053152991),4326), 149, 'pTRzho5qf', '2022-04-06 20:36:49',	'374283476459383');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.493211740992518,-33.98326961280045),4326), 263, '2k6zFW2fV', '2022-02-13 04:28:51',	'374288512927079');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.582287505068194,-34.0323173209878),4326), 173, 'NvTL1utgl', '2022-02-03 10:31:07',	'374288722261160');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.611706674556217,-34.051271803177386),4326), NULL, 'u69NfAF6m', '2022-02-04 23:37:52',	'374288102282406');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.493686415367904,-34.02243521843036),4326), 305, 'muEM60B60', '2022-04-23 17:41:02',	'374288936462778');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.48685781483512,-34.01457717940077),4326), 412, 'UAcHcA5Fz', '2022-03-26 17:32:47',	'374283951041094');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5631663025027,-34.02236928839622),4326), NULL, 'QSg99pB5E', '2022-04-01 23:43:43',	'374283252311048');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.525165948898792,-34.015910811781715),4326), 378, '2YVzAqCgB', '2022-04-14 08:37:35',	'374283753632678');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5519533653254,-34.00332057524923),4326), 390, 'Q7QT2aGcs', '2022-02-24 18:41:21',	'374283798402327');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.528232171753583,-34.01401053086664),4326), 186, 'kKxbnCGsT', '2022-03-16 16:54:58',	'374283237263934');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.547702209311375,-34.02214393793832),4326), 101, 'TB2l7VnGJ', '2022-04-02 16:11:30',	'374283564711653');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.534582440341524,-34.00449220456332),4326), 118, 'L6Bxwcyg9', '2022-04-30 06:55:04',	'374283639666106');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57242145230501,-34.01776008070104),4326), 363, '81HwY2jAD', '2022-04-10 06:51:45',	'374283267922078');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.526343821608982,-34.00441133753946),4326), 276, 'nTUtDBryz', '2022-03-31 17:36:04',	'374283321304826');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.493569772885344,-33.96827934072452),4326), 280, 'vhKQZygIx', '2022-02-05 04:18:27',	'374288881735806');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.512359626448117,-33.98665534179344),4326), 161, 'H18J0ff2Z', '2022-03-10 05:22:45',	'374283572971463');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.50720540910241,-33.98818422438918),4326), 200, 'xRZeTF6vp', '2022-04-04 22:33:27',	'374283092556158');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.53334668586231,-34.03448122749569),4326), 244, 'eqRkbop1y', '2022-02-06 08:02:29',	'374288683120009');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.541788755744978,-34.0502096930721),4326), 179, 'q9EeLFfnr', '2022-04-20 22:19:26',	'374283454872748');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.517433414298598,-34.024848893191724),4326), 199, 'lhk4UZDMo', '2022-03-16 02:32:26',	'374288689012887');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.570587520146194,-34.05127837379851),4326), 326, 'oUaw2MlXe', '2022-02-25 19:09:23',	'374283769017393');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.49009405352229,-34.03166258024132),4326), 367, 'eUco81Ka4', '2022-03-29 10:14:52',	'374283222808743');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.471013177723183,-34.0345625858613),4326), 92, 'hWM6bozlJ', '2022-04-23 07:09:18',	'374288104072284');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57905659765455,-33.98356318248408),4326), 187, 'DL4rmn2YL', '2022-02-08 17:11:03',	'374288948175863');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.55767397400703,-34.047846160366646),4326), 215, 'LCe1kZPtA', '2022-03-02 14:13:27',	'374283505235051');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.532251585903616,-34.04406481568652),4326), 390, 'kJq7fgEit', '2022-03-20 13:25:04',	'374288066944926');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.498804356550828,-33.9819127940703),4326), 321, '94TICObbW', '2022-02-08 22:44:44',	'374288215404608');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.470231291151727,-34.01946113642653),4326), 421, 'PluuUfjXR', '2022-03-10 19:46:49',	'374283618084909');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.54971430065113,-33.9261516075308),4326), 144, 'TnODr7hIW', '2022-04-05 20:00:28',	'374283585705650');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.529371857383275,-34.06856845222363),4326), 50, 'M5hfRdX4F', '2022-03-16 15:59:11',	'374283610969529');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.60817764964333,-34.05119319970105),4326), 380, 'OfRxEIcTB', '2022-03-07 12:40:08',	'374283562574475');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.421042389937313,-33.93004141972568),4326), 174, 'mJVgvioZt', '2022-04-11 03:54:02',	'374283616280442');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.574275304875272,-34.07041723100176),4326), 107, 'VKbHHhVu1', '2022-03-11 04:14:39',	'374283112131297');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.420856370247037,-34.07725374031092),4326), 359, 'QlL1RZNLy', '2022-03-13 21:44:18',	'374283813325404');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52816087574993,-33.92313253798916),4326), 162, 'U9U8LsclO', '2022-04-14 06:26:37',	'374288065477878');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.39566157422292,-34.00371433736607),4326), 365, 'T8vHWn8Zq', '2022-02-08 13:48:31',	'374288670410280');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.551065134870683,-33.9301609002325),4326), 139, '5qD0Drrvt', '2022-02-17 14:46:48',	'374288750736059');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.467208053919638,-34.08650121673805),4326), 255, 'eqZqa8Q6L', '2022-02-15 14:47:50',	'374288099326638');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.4009488903944,-33.99421932033073),4326), 419, 'qRiT08st1', '2022-04-16 04:44:39',	'374283088600309');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.459743908268408,-33.947177968921956),4326), 116, 'KZJDlHL32', '2022-03-06 07:04:47',	'374288013359830');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.58558707734559,-33.956863502081276),4326), 418, 'ZkAHCaTsX', '2022-03-12 13:05:02',	'374283724656236');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.407708029623304,-34.07039080610039),4326), 287, 'zLvf7aVnq', '2022-03-04 08:11:04',	'374283955480066');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.409936037145325,-33.93043070019519),4326), 475, 'YX54wlZTi', '2022-04-07 06:58:33',	'374288142475465');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.418280567718924,-33.92069552505126),4326), 493, '8Krr7ybtH', '2022-04-05 19:50:10',	'374288902428035');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.4281215510029,-33.918452639916886),4326), 55, '2Gf3nxsJW', '2022-04-14 08:28:03',	'374283612413435');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.41571643933481,-33.92540669593457),4326), 455, '52yeFbmXW', '2022-02-13 08:51:55',	'374283506412964');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.423967684133096,-33.92799030474655),4326), 433, 'lMuuL10CT', '2022-03-30 00:18:38',	'374283875640344');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.434548419480393,-33.912811250470966),4326), 309, 'aJcuFZP6M', '2022-03-29 12:20:50',	'374288046504980');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.60153816226314,-34.04768746817902),4326), 175, 'h4pPBPHBp', '2022-04-24 21:51:33',	'374283068636315');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.600098085299482,-34.05317518651471),4326), 179, 'LzD78SYit', '2022-03-18 03:10:18',	'374283752749598');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59701388632013,-34.05043698656939),4326), 426, 'ApSFX8bZD', '2022-04-23 05:00:15',	'374283629331083');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.596737455435893,-34.04763975087918),4326), 155, '6JWrkeHm3', '2022-03-29 07:20:32',	'374283232752220');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59135693201404,-34.05602616368488),4326), 203, '2vjZnnokw', '2022-02-09 18:27:11',	'374283773274261');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.598283557313792,-34.072832542860695),4326), 155, 'rrZOpuv9W', '2022-04-11 07:28:54',	'374288427397764');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5912160006812,-34.04197064453391),4326), 176, 'SHeTlcPgk', '2022-04-25 04:18:44',	'374283875122749');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59924820140573,-34.060776274012056),4326), 141, 'uODXg3Ada', '2022-03-01 18:10:22',	'374288302711469');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.59009345842844,-34.03575247472216),4326), NULL, '7djB6kHR2', '2022-04-25 21:31:55',	'374288539198753');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.380529500333378,-34.02796925549625),4326), 183, 'ObcqL5aYo', '2022-02-16 15:52:39',	'374288935577154');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.377315551704644,-34.028525287193446),4326), 275, '3X9XcSTNL', '2022-04-16 09:32:58',	'374283837534171');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.364510570304404,-34.040525172589625),4326), 143, 'NpSpxru8u', '2022-04-21 11:07:33',	'374288241777464');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.382685065475535,-34.04638852194807),4326), 177, 'k90kBTseq', '2022-04-21 05:53:36',	'374288591459846');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.375581877305148,-34.01667805383258),4326), 208, 'l61nD2AFI', '2022-03-03 20:22:52',	'374283239673270');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.394492133031008,-34.053568710510625),4326), 234, 'kG2fiNr20', '2022-02-15 16:17:33',	'374288868320838');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.33176375591087,-34.02023112696758),4326), 89, 'I2QHDw2fT', '2022-03-28 00:12:14',	'374288950480078');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.398596904136543,-34.06161121206856),4326), 128, 'ezq7RXAlB', '2022-04-14 07:38:00',	'374288842093519');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.360632037146942,-34.00498806796476),4326), 267, 'FRrkEC7Nd', '2022-03-06 21:08:25',	'374288669712043');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.378670856853837,-34.07226606041685),4326), 377, '0EwJTu425', '2022-04-21 07:49:36',	'374288599025110');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.401840689165855,-34.02564421724198),4326), 254, 'vz0xNrlId', '2022-04-30 13:21:56',	'374283336332085');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.417251720756866,-33.979407907325),4326), 182, 'zzKkuLgqi', '2022-02-03 23:14:52',	'374288900426825');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.415845651291797,-33.98989314677198),4326), 431, 'nqXbQyMCP', '2022-02-21 05:09:43',	'374283353113335');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.41436871314943,-33.985276307965194),4326), 339, 'qILCYKe5T', '2022-03-08 05:02:44',	'374288010077419');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.428976599820356,-34.00089239076129),4326), 127, 'gcEaw1dVJ', '2022-02-08 13:00:48',	'374283985749720');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.390647171772915,-33.96343752155134),4326), 50, 'ld3l1hkKJ', '2022-02-16 09:42:48',	'374288617608004');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.409424588425747,-33.9776396375221),4326), 493, 'hGN7QrjXt', '2022-02-19 00:03:25',	'374288345478589');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57978925012071,-33.92228610118504),4326), 167, 'vCU1kfj0O', '2022-04-04 12:55:14',	'374288833403107');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.566553605977617,-33.925461734284475),4326), 223, 'kjSrGKL3z', '2022-04-28 12:19:24',	'374283734357783');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.57782251622167,-33.94184640135363),4326), 455, 'QatTV516r', '2022-04-07 21:59:54',	'374288192263977');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.586969361028892,-33.92296181172713),4326), 352, 'nZF2kw862', '2022-03-12 20:37:17',	'374283785643974');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.56070905993196,-33.91080558960179),4326), 488, 'XD6rq9iRQ', '2022-04-15 19:37:34',	'374283478184948');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.578152271809167,-33.93785130769884),4326), 443, 'v7lRwW91w', '2022-04-26 09:17:02',	'374288842403114');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.576721440300947,-33.93680055570521),4326), 452, 'MG5XtEK79', '2022-04-02 06:57:07',	'374288580763042');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.586667038570376,-33.919946513538925),4326), 208, 'JY8BHJtiP', '2022-02-23 12:11:37',	'374283289306060');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.60878097698769,-33.970844011067086),4326), 390, 'FbisbmDSc', '2022-02-21 05:48:08',	'374288800438631');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.603397455464354,-33.9858208158201),4326), 298, 'SOrmPVuyg', '2022-03-13 14:37:16',	'374283000212787');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.596554040491856,-33.96726658398006),4326), 494, 'XBk7EkU0R', '2022-02-25 22:10:40',	'374283063976781');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.625603962207943,-33.983313579621615),4326), 399, 'bqOm6gUQw', '2022-04-28 22:01:00',	'374283340682657');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.62928844322349,-33.966926525972575),4326), NULL, 'asJrOQagd', '2022-03-20 12:19:35',	'374283374046175');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.617215969544766,-33.982694439478834),4326), 263, 'keRhrAMPT', '2022-03-17 22:34:06',	'374283568510358');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.617711478880974,-33.95779682181157),4326), 152, 'y9cfEF7s5', '2022-03-15 17:21:08',	'374288147671415');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.61270350660183,-33.953061426475834),4326), 274, 'xrVwhvFlE', '2022-04-07 21:04:12',	'374283347357162');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.599474596051188,-33.99125928578268),4326), 251, 'Za8p6VKCn', '2022-04-09 19:24:43',	'374288507647963');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.620143490156128,-33.963128521357355),4326), 380, 'dKaJaGPTa', '2022-04-17 04:28:25',	'374283346597784');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.477707314168264,-34.03316647572601),4326), 436, 'uH1jZPA6n', '2022-04-15 17:57:22',	'374288587526871');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.48127660088741,-34.02849530362909),4326), 65, 'VuTkhtJyM', '2022-02-28 13:04:30',	'374288319586045');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.48028416810564,-34.05266286790303),4326), 441, 'fOF9KqomZ', '2022-03-15 04:02:38',	'374283783003353');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.464647304634376,-34.04101194260216),4326), 339, '9boz2h56H', '2022-04-24 23:31:41',	'374283101514289');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52206375136366,-34.07186263316177),4326), 412, 'qXZO15cYF', '2022-04-03 08:45:53',	'374283831383955');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52694837509784,-34.075691985004795),4326), 82, 'pF55aGrBi', '2022-04-18 02:26:36',	'374288816254121');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.521542568894006,-34.053119129364),4326), 101, 'Qklpvq6cZ', '2022-04-05 21:55:35',	'374283411414766');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.502506470763944,-34.09764604167484),4326), 247, 'LiU6mHxO9', '2022-04-15 05:38:06',	'374283407598754');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.534049094415217,-34.04832682565349),4326), 239, '1xKDrvcYj', '2022-02-10 07:09:01',	'374283434329801');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.52406108676878,-34.09092925597436),4326), 278, '6t60Q6tRo', '2022-04-19 06:19:33',	'374288490199451');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.499704621421778,-34.07089842946392),4326), 238, 'UgrJYkWwS', '2022-03-15 12:07:20',	'374283821123684');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.433958477867314,-34.035032477051075),4326), 370, 'hnLerKsUG', '2022-03-28 12:20:37',	'374283210224333');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.442626764197204,-34.02932019349219),4326), 235, 'pk7ePabyx', '2022-04-04 00:56:55',	'374283513948323');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.426163858051428,-34.031303858101474),4326), 76, 'aNYfsarlG', '2022-03-28 10:51:22',	'374283734804321');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.41633739773688,-34.04830352920991),4326), 467, 'U8fjM4DKE', '2022-03-07 00:38:33',	'374288360033681');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.440832329046955,-34.09434852929799),4326), 180, 'INnHuaVFT', '2022-04-23 11:46:53',	'374283383011897');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.432048418565905,-34.09222882831818),4326), 261, 'Kc70kIyTQ', '2022-03-30 03:16:26',	'374288214549510');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.44799712081154,-34.08693573218294),4326), 268, 'P9mb199ix', '2022-03-23 23:46:58',	'374288474841649');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.416625158880223,-34.102145185848535),4326), 78, 'fbfdQbI5v', '2022-02-10 06:42:57',	'374283014741896');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.45485999485604,-34.07137345361716),4326), 123, 'J6t764BVI', '2022-03-12 11:39:47',	'374283080887193');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.455709451043035,-34.089740414951194),4326), 261, 'TxL7IFs5W', '2022-04-10 15:10:02',	'374288248593880');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.43303640097564,-34.07708635757535),4326), 312, 'GLuGaB2DI', '2022-02-01 16:50:05',	'374283035973692');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.427033015352556,-34.06894922285573),4326), 72, 'EZlWEcR7i', '2022-02-14 12:28:03',	'374283457970788');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.458677659211705,-34.1027608962014),4326), 146, 'V4Iflzd6G', '2022-02-15 20:46:46',	'374283417772282');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.48744503156378,-34.099729800543244),4326), 366, 'FtiCxCFPo', '2022-03-16 13:14:04',	'374283366197317');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.451916364366998,-34.1139176097714),4326), 153, 'STanJ2C6a', '2022-02-28 09:41:51',	'374283572092666');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.467453528401265,-34.11755459532145),4326), 86, '0SfkIcnpM', '2022-04-23 09:29:24',	'374288346378010');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.506393720623993,-33.978772090896925),4326), 285, 'aO17UD2SB', '2022-04-23 22:15:25',	'374283249168014');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.49479794626627,-33.978019090943356),4326), 64, 'UyqJZBBXK', '2022-04-08 22:41:51',	'374288323151356');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.497994715399454,-33.99188679327897),4326), 122, '4Ivn5g3yC', '2022-04-23 09:46:54',	'374283061515052');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.50656435329343,-33.981012267670835),4326), 334, 'rMxx8rgtO', '2022-04-28 02:33:59',	'374283143369007');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.453514251685647,-33.942773637688944),4326), 77, 'iRBnCcJUM', '2022-02-26 07:45:35',	'374283161582275');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.467682459472957,-33.94687416662543),4326), 440, 'T4rItXQTN', '2022-03-18 06:32:42',	'374288056534166');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.46591309955283,-33.941998474558005),4326), 237, 'dvoSN5Asg', '2022-04-30 23:21:28',	'374288622094471');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.453728459888946,-33.96607152464896),4326), 184, 'i21ctO4cg', '2022-04-16 23:51:08',	'374288742722639');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.46643912987239,-33.98805148914497),4326), 65, 'ngErCf1fB', '2022-02-20 22:18:49',	'374283532393931');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.469453021008096,-34.000570602884125),4326), 466, 'we0wca7aB', '2022-04-25 00:34:27',	'374283711373266');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.467781398840287,-34.00595840685318),4326), 269, 'aSQk31GtR', '2022-04-22 16:09:35',	'374288433734810');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.467124202525348,-33.982500557883114),4326), NULL, 'ccbzRvV4u', '2022-02-28 13:31:59',	'374283951689819');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.510170026136336,-34.01792871061993),4326), 205, 'ExV93nSSm', '2022-02-13 11:57:48',	'374288394912553');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.514638464730346,-34.02635456418946),4326), 265, 'XvNcl6OUQ', '2022-02-01 01:50:47',	'374288205028706');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.518255365754843,-34.02486447624965),4326), 287, '1okdA2yQl', '2022-02-10 11:55:51',	'374288913936224');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.509576928448574,-34.00250278184846),4326), 122, 'aJmH76ikI', '2022-03-24 14:26:13',	'374288998272230');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.497141576679564,-33.91433764618926),4326), 331, 'UDXQS01yB', '2022-04-01 08:47:50',	'374283686638917');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.501934688372504,-33.914408452145516),4326), 287, 'n7wyV5UDs', '2022-04-16 00:51:57',	'374288191443125');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.50950370190764,-33.9008243620288),4326), 277, 'U0t8YgcJT', '2022-02-18 16:34:12',	'374283615659786');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.484285151044176,-33.90801741854955),4326), 140, 'Fawx75RlU', '2022-04-12 14:03:22',	'374283404264012');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.509007129408552,-33.91218386747463),4326), 479, 'qr5TSG4bv', '2022-02-28 16:09:11',	'374283407489772');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.49924304918076,-33.9247471425189),4326), 115, 'LODWyrt03', '2022-03-20 00:17:38',	'374283890812530');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.546231105984493,-33.962692029264375),4326), NULL, 'jlpgE3bVW', '2022-03-19 08:14:01',	'374288536765109');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.537615991107085,-33.97375908674232),4326), 165, 'INTMwOGq4', '2022-04-06 18:53:37',	'374288073520438');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.537436212942534,-33.96448856269974),4326), 408, 'X30YCFbus', '2022-03-10 13:21:36',	'374288169735270');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.537741052485547,-33.944284747757365),4326), 376, 'nkIBJxfZ2', '2022-03-29 21:52:20',	'374283516968492');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.5514101932342,-34.01624499576817),4326), 143, 'bf0MUy9NF', '2022-04-03 16:45:02',	'374283617004148');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.543303374174556,-34.00802247234844),4326), 122, 'D1D72G3x8', '2022-02-11 04:34:12',	'374288534507016');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.538215070703842,-34.01547119196355),4326), 369, 'CziwJ4ja9', '2022-04-30 05:11:45',	'374288324650604');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.538519730106128,-34.01289121519785),4326), NULL, 'DpiCa1E00', '2022-03-04 00:59:11',	'374288591804868');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.537674470714347,-34.006054855609904),4326), 242, 'RJhHcoRjw', '2022-03-31 18:04:39',	'374288538986133');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.566339285771576,-34.01562210756357),4326), 130, 'LFqaYJk1w', '2022-02-13 03:14:54',	'374283306864893');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.550287054636204,-34.00211393238606),4326), 289, '1QnmqwQHA', '2022-03-04 12:43:47',	'374283020834651');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.53567886133103,-34.01457568255077),4326), NULL, 'wmEVAyrkf', '2022-03-29 19:42:11',	'374288006515901');
INSERT into DemoLabExam2aTable (cloc, amount, checksum, ccTS,creditcard) VALUES (ST_SetSRID(ST_MakePoint(18.536410011360207,-34.03126745649801),4326), 268, 'i2fAF1S7U', '2022-03-05 15:58:35',	'374283904981107');

-- visual check for the contents of the table
SELECT ST_AsTEXT(cloc), amount, checksum,ccts,creditcard from DemoLabExam2aTable LIMIT 20;


select count(*) from DemoLabExam2aTable;

--QUESTION 1: Some suspicious credit card activity has been detected and you are asked to delete
--rows from the table which have the following criteria – the amount is less than 150 Zar and the final
--digit in the credit card number is less than or equal to 5.

select * from DemoLabExam2aTable where amount < 150 and creditcard ~ '^.*[012345]$';

-- nrow = 41

select amount,creditcard from DemoLabExam2aTable where amount < 150 and creditcard ~ '^.*[012345]$';

Delete from DemoLabExam2aTable where amount < 150 and creditcard ~ '^.*[012345]$';


--QUESTION 2: A shop within Cape Town Airport has Longitude 18.596978 and Latitude -33.968993.
--Consider all rows where the location (cloc) of the transactions are less than 5KM from this location.
--Update the amount in all rows to the exact value of 456 Zar where the amount is already greater
--than 400 or currently contains a NULL value.

select * from DemoLabExam2aTable where ST_DISTANCE(st_transform(cloc,2055),st_transform(ST_GeomFromText('POINT(18.596978 -33.968993)',4326)
,2055))/1000 < 5 and ( amount > 400 or amount is NULL);

select ST_SRID(cloc) from DemoLabExam2aTable LIMIT 10;

update DemoLabExam2aTable set amount = 456 where ST_DISTANCE(st_transform(cloc,2055),st_transform(ST_GeomFromText('POINT(18.596978 -33.968993)',4326)
,2055))/1000 < 5 and ( amount > 400 or amount is NULL);
--nrow = 19

--QUESTION 3: Consider the credit cards such as 374288950480078 , 374283775330189, and
--374283336332088. The last four digit characters (duplicates allowed) when considered or read as a
--four-digit number have a numerical value of less than 2,500. In these three examples, the numbers
--are 78, 189 and 2,088 (leading zeros are allowed).
--Write an SQL query which will delete all rows from this table where the last four digits of the credit
--card number, when considered as a four digit number, has a numerical value of less than 2,500.

select * from DemoLabExam2aTable where creditcard ~ '^.*([0-1][0-9]{3}|[2][0-4][0-9]{2})$';

--nrow = 53

select * FROM DemoLabExam2aTable
WHERE CAST(RIGHT(creditcard, 4) AS INTEGER) < 2500;

Delete from DemoLabExam2aTable where creditcard ~ '^.*([0-1][0-9]{3}|[2][0-4][0-9]{2})$';


--QUESTION 4: Update the table as follows. Set the amount column to NULL where the corresponding
--checksum ends with four alphabetical characters (no digits, repeated characters allowed) and the
--amount is less than 300 Zar.


SELECT ST_AsTEXT(cloc), amount, checksum,ccts,creditcard from DemoLabExam2aTable LIMIT 20;

select amount,checksum from DemoLabExam2aTable where amount < 300 and checksum ~ '^.*[a-zA-Z]{4}$';

update DemoLabExam2aTable set amount = NULL where amount < 300 and checksum ~ '^.*[a-zA-Z]{4}$';

--nrow = 43

--QUESTION 5: Delete all rows (where the amount is NOT currently null) where the ccts timestamp
--indicates that the transactions occurred on or after 9am but before 9pm on any day in April.

select * from DemoLabExam2aTable LIMIT 10;

select * from DemoLabExam2aTable where amount is not NULL and date_part('month',ccts) = 4 and 
(date_part('hour',ccts) >= 9 and date_part('hour',ccts) < 21);

--select * from DemoLabExam2aTable where amount is NULL and date_part('month',ccts) = 4 and 
--(date_part('hour',ccts) >= 9 and date_part('hour',ccts) < 21);

--WHERE amount IS NOT NULL AND ccts::time >= TIME '09:00:00'
--AND ccts::time < TIME '21:00:00' AND EXTRACT(MONTH FROM ccts) = 4

Delete from DemoLabExam2aTable where amount is not NULL and date_part('month',ccts) = 4 and 
(date_part('hour',ccts) >= 9 and date_part('hour',ccts) < 21);

--nrow = 25

--QUESTION 6: Given the following WKT POINT (expressed in EPSG:4326) POINT (18.57235 -
--34.01127). Update the table by setting the cloc column equal to this point location where the
--amount currently is a NULL value and the checksum begins with any digit.

SELECT ST_AsTEXT(cloc), amount, checksum,ccts,creditcard from DemoLabExam2aTable LIMIT 20;

--update DemoLabExam2aTable set ST_AsTEXT(cloc) = 'POINT (18.57235 34.01127)' where amount is NULL and checksum ~ '^\d.*$';

UPDATE DemoLabExam2aTable
SET cloc = ST_GeomFromText('POINT(18.57235 -34.01127)', 4326)
WHERE amount IS NULL
  AND checksum ~ '^\d.*$';

--nrow = 8

--QUESTION 7: Given the WKT expressed POINT as POINT(1337778.535 3861633.96) which is already
--provided to you in EPSG:2055, write a query to delete all rows in the table where the geographic
--location in cloc is less than 2.5KM from this point.


select count(*) from DemoLabExam2aTable;

--select * from DemoLabExam2aTable where ST_DISTANCE(ST_GeomFromText('POINT(1337778.535 3861633.96)',2055),
--st_transform(cloc,2055))/1000 < 2.5;

Delete from DemoLabExam2aTable where ST_DISTANCE(ST_GeomFromText('POINT(1337778.535 3861633.96)',2055),
st_transform(cloc,2055))/1000 < 2.5;

--nrow = 21

--QUESTION 8. For ANY day in the table, on or after 3 o’clock, in the afternoon, delete all rows where
--the credit card number has 5 or more consecutive digits between 2 and 7 (both inclusive). For
--example 37428307223336331 or 37428302235235331 are examples of these credit card numbers.

SELECT ST_AsTEXT(cloc), amount, checksum,ccts,creditcard from DemoLabExam2aTable LIMIT 10;

select * from DemoLabExam2aTable where date_part('hour',ccts) >= 15 and creditcard ~ '.*[2-7]{5,}.*';

Delete from DemoLabExam2aTable where date_part('hour',ccts) >= 15 and creditcard ~ '.*[2-7]{5,}.*';

--nrow = 9